// Generated by CoffeeScript 1.3.1
(function() {
  var SnapHelper;

  SnapHelper = (function() {

    function SnapHelper() {}

    SnapHelper.prototype.directionalSnap = function(obj_being_snapped, obj_snapped_to, direction, duration) {
      if (duration == null) {
        duration = 0;
      }
    };

    return SnapHelper;

  })();

}).call(this);
